config/routes.rb
Rails.application.routes.draw do  
  scope "(:locale)" do
    devise_for :users

    get 'pages/home'
    get '/about',             to: 'pages#about'
    get '/privacy_policy',    to: 'pages#privacy_policy'   
    #get '/products',          to: 'pages#products'
    get 'purchases/show',     to: 'purchases#show'
    #get '/retreat',           to: 'pages#retreat'
    get '/services',          to: 'pages#services'
    get '/store_index',       to: 'store#index'
    get 'tags/:tag',          to: 'blogs#index', as: :tag
    get '/terms_of_service',  to: 'pages#terms_of_service'

    resources :blogs do 
      member do 
        get :toggle_status
      end
      get 'page/:page', action: :index, on: :collection
    end
    resources :carts
    resources :charges
    resources :contacts, only: [:new, :create]
    resources :leads
    resources :line_items
    resources :orders
    resources :photos
    resources :products do
      get :who_bought, on: :member
    end
    resources :purchases, only: [:show]
    resources :retreats do
      get '/import', action: :import, on: :collection
    end
    resources :subscriptions
    resources :teachers
    resources :topics, only: [:index, :show]

    mount ActionCable.server => '/cable'
  
    root to: 'pages#home'
  end
end

app/models/retreat.rb
class Retreat < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, :overview, :start_date, :end_date, presence: true

  scope :reverse_date_order, -> { order("retreats.created_at DESC") }
end

app/controllers/retreats_controller.rb
class RetreatsController < ApplicationController
  before_action :set_retreat, only: [:show, :edit, :update, :destroy ]
  access [:all, :user] => [:show, :index], teacher: :all, site_admin: :all

  def index
    @retreats = Retreat.all.reverse_date_order.paginate(page: params[:page], per_page: 3)
  end

  def show
  end

  def new
    @retreat = Retreat.new
  end

  def create
    @retreat = Retreat.new(retreat_params)
    if @retreat.save
      flash[:notice] = "#{t(:retreat)} #{t(:created)}"
      redirect_to retreats_path
    else
      render :index
    end
  end

  def edit
  end

   def update
    if @retreat.update(retreat_params)
      flash[:notice] = "#{t(:retreat)} #{t(:updated)}"
      redirect_to retreats_path
    else
      render :edit
    end
  end

  def destroy
    @retreat.destroy
    flash[:notice] = "#{t(:retreat)} #{t(:deleted)}"
    redirect_to retreats_path
  end

  def import
    domain = ENV['RGBDOMAIN']
    token  = ENV['RGBTOKEN']

    if domain && token
      url = "#{domain}#{token}"
      resp = Net::HTTP.get_response(URI.parse(url))
      retreats = JSON.parse(resp.body).select { |retreat| retreat["categories"] == ["application"] }

      imported_retreats = 0

      retreats.each do |rbg_retreat|
        unless Retreat.exists?(rbg_id: rbg_retreat["id"].to_s)
          retreat = Retreat.new
          retreat.name              = rbg_retreat["name"]
          retreat.overview          = rbg_retreat["name"]
          retreat.start_date        = rbg_retreat["start_date"]
          retreat.end_date          = rbg_retreat["end_date"]
          retreat.teachers          = rbg_retreat["teachers"].join(", ")
          retreat.location          = rbg_retreat["location"]
          retreat.address           = rbg_retreat["address"]
          retreat.available_spaces  = rbg_retreat["available_spaces"]
          retreat.program_link      = rbg_retreat["program_link"]
          retreat.registration_link = rbg_retreat["registration_link"]
          retreat.thumb_nail        = rbg_retreat["images"]["medium"]["url"]
          retreat.main_image        = rbg_retreat["images"]["large"]["url"]
          retreat.rbg_id            = rbg_retreat["id"].to_s

          if retreat.save
            imported_retreats += 1
          else
            flash[:alert] = "Error in saving retreat: " + rbg_retreat["id"].to_s
          end
        end
      end
      
      flash[:notice] = imported_retreats.to_s + " retreats were imported"
      redirect_to retreats_path
    
    else
      # One or both environment variables not retrieved
      flash.now[:alert] = "Domain: #{domain} or token: #{token} not set"
      render :index
    end
  end

  private
    
    def retreat_params
      params.require(:retreat).permit(:name, :overview, :body, :start_date, 
        :end_date, :teachers, :location, :address, :available_spaces, 
        :program_link, :registration_link, :thumb_nail, :thumb_mail_cache, 
        :main_image, :main_image_cache, :rgb_id)
    end

    def set_retreat
      @retreat = Retreat.friendly.find(params[:id])
    end

end

app/helpers/retreats_helper.rb
module RetreatsHelper
end

app/views/retreats/_form.html.erb
<%= render 'shared/errors', obj: @retreat %>
<%= form_for @retreat do |f| %>
<div class= "col-sm-12">
  <div class="form-group">
    <%= f.label t(:name), class: ('required' if required?(@retreat, :name)) %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:overview), class: ('required' if required?(@retreat, :overview)) %>
    <%= f.text_field :overview, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:start_date), class: ('required' if required?(@retreat, :name)) %>
    <%= f.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:end_date), class: ('required' if required?(@retreat, :name)) %>
    <%= f.date_field :end_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:teachers), class: ('required' if required?(@retreat, :teachers)) %>
    <%= f.text_field :teachers, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:location), class: ('required' if required?(@retreat, :location)) %>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label t(:address), class: ('required' if required?(@retreat, :address)) %>
    <%= f.text_area :address, class: 'form-control', rows: '5' %>
  </div>
   <div class="form-group">
    <%= f.label t(:available_spaces), class: ('required' if required?(@retreat, :available_spaces)) %>
    <%= f.number_field :available_spaces, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:program_link), class: ('required' if required?(@retreat, :program_link)) %>
    <%= f.text_field :program_link, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:registration_link), class: ('required' if required?(@retreat, :registration_link)) %>
    <%= f.text_field :registration_link, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="btn btn-secondary">
      <%= t(:upload_main_image_file) %> <%= f.file_field :main_image,
          style: "display:none;" %>
    </label>
  </div>
  <div class="form-group">
    <label class="btn btn-secondary">
      <%= t(:upload_thumb_nail_file) %> <%= f.file_field :thumb_nail,
          style: "display:none;" %>
    </label>
  </div>
  <div class="form-group">
    <%= f.label t(:body), class: ('required' if required?(@retreat, :body)) %>
    <%= f.hidden_field :body, class: 'form-control', rows: '15', id: "retreat_body" %>
    <trix-editor input="retreat_body"></trix-editor>
  </div>
  <div class="form-group">
    <%= f.label t(:rbg_id), class: ('required' if required?(@retreat, :rbg_id)) %>
    <%= f.text_field :rbg_id, class: 'form-control' %>
  </div>

  <%= f.submit(@retreat.new_record? ? t(:create): t(:save), class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/retreats/_retreat.html.erb
<div class="card retreat">
  <%= link_to(image_tag(retreat.thumb_nail, 
    options = {class: 'card-img-top'}), retreat_path(retreat)) %>
  <div class="card-body">
    <h4 class="card-title"><%= link_to retreat.name, retreat_path(retreat) %></h4>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= retreat.teachers %></li>
    <li class="list-group-item"><%= t(:start_date) %> <%= retreat.start_date %>
    <li class="list-group-item"><%= t(:end_date) %> <%= retreat.end_date %></li>
  </ul>
  <div class="card-body">
    <%= link_to(t(:program_link), retreat.program_link, target: :_blank) %>
    <%= link_to(t(:registration_link), retreat.registration_link, target: :_blank) %>
    <% if logged_in?(:site_admin, :teacher) %>
        <ul class="actions mt-2">
        <li><%= link_to t(:edit), edit_retreat_path(retreat), class: "btn btn-primary" %></li>
        <li><%= link_to t(:delete), retreat_path(retreat), class: "btn btn-danger", 
            method: :delete, data: { confirm: t(:are_you_sure) } %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/retreats/edit.html.erb
<div class="page-header">
  <%= render 'shared/page_title', title: t(:retreat_edit_title) %>
  <ul class="actions">
    <li><%= link_to t(:index), retreats_path, class: "index" %></li>
    <li><%= link_to t(:delete), retreat_path, class: "delete", 
            method: :delete, data: { confirm: t(:are_you_sure) } if logged_in?(:site_admin, :teacher)%></li>
  </ul>
</div>
<div class="container">
  <%= render 'form' %>
</div>

app/views/retreats/index.html.erb
<div class="page-header">
  <%= render 'shared/page_title', title: t(:retreat_index_title) %>
  <ul class="actions form-inline">
    <li><%= link_to t(:new), new_retreat_path, class: "new" if logged_in?(:site_admin, :teacher) %></li>
    <li><%= link_to t(:import), import_retreats_path, class: "import" if logged_in?(:site_admin) %></li>
  </ul>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="row justify-content-center">
      <%= will_paginate @retreats %>
    </div>
    <div class="card-deck">
      <%= render @retreats %>
    </div><br />
    <div class="row justify-content-center">
      <%= will_paginate @retreats %>
    </div>
 </div>
</div>

app/views/retreats/new.html.erb
<div class="page-header">
  <%= render 'shared/page_title', title: t(:retreat_new_title) %>
  <ul class="actions">
    <li><%= link_to t(:index), retreats_path, class: "index" %></li>
  </ul>
</div>
<div class="container">
  <%= render 'form' %>
</div>

app/views/retreats/show.html.erb
<div class="page-header">
  <%= render 'shared/page_title', title: t(:retreat_show_title) %>
  <ul class="actions">
    <li><%= link_to t(:index),  retreats_path, class: "index" %></li>
    <% if logged_in?(:site_admin, :teacher) %>
      <li><%= link_to t(:edit),   edit_retreat_path(@retreat), class: "edit" %></li>
      <li><%= link_to t(:delete), retreat_path, class: "delete", 
              method: :delete, data: { confirm: t(:are_you_sure) } %></li>
    <% end %>
  </ul>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <%= image_tag @retreat.main_image, width: "400" %>
    </div>
    <div class="col-sm-6">
      <h4><%= @retreat.name %></h4>
      <h6 class="text-muted"><%= @retreat.overview %></h6>
        <p><%= t(:location) %>: <%= @retreat.location %></p>
        <P><%= t(:address) %>: <%= @retreat.address %></P>
        <P><%= t(:available_spaces) %>: <%= @retreat.available_spaces %></P>
        <p>Cost: USD 8,000 plus accommodation</p>
        <p><%= t(:teachers) %>: <%= @retreat.teachers %></p>
        <p><%= t(:start_date) %> : <%= @retreat.start_date.strftime('%v') %></p>
        <p><%= t(:end_date) %> : <%= @retreat.end_date.strftime('%v') %></p>
        <p><%= link_to(t(:program_link), @retreat.program_link, target: :_blank) %></p>
        <p><%= link_to(t(:registration_link), @retreat.registration_link, target: :_blank) %></p>
    </div>
    <div class="col-sm-12">
    <p><%= sanitize @retreat.body %></p> 
  </div>
</div>