config/routes.rb
Rails.application.routes.draw do  
  scope "(:locale)" do
    devise_for :users

    get 'pages/home'
    get '/about',             to: 'pages#about'
    get '/privacy_policy',    to: 'pages#privacy_policy'   
    #get '/products',          to: 'pages#products'
    get 'purchases/show',     to: 'purchases#show'
    #get '/retreat',           to: 'pages#retreat'
    get '/services',          to: 'pages#services'
    get '/store_index',       to: 'store#index'
    get 'tags/:tag',          to: 'blogs#index', as: :tag
    get '/terms_of_service',  to: 'pages#terms_of_service'

    resources :blogs do 
      member do 
        get :toggle_status
      end
      get 'page/:page', action: :index, on: :collection
    end
    resources :carts
    resources :charges
    resources :contacts, only: [:new, :create]
    resources :leads
    resources :line_items
    resources :orders
    resources :photos
    resources :products do
      get :who_bought, on: :member
    end
    resources :purchases, only: [:show]
    resources :retreats do
      get '/import', action: :import, on: :collection
    end
    resources :subscriptions
    resources :teachers
    resources :topics, only: [:index, :show]

    mount ActionCable.server => '/cable'
  
    root to: 'pages#home'
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  acts_as_taggable
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  belongs_to :topic
  has_many :comments, dependent: :destroy
  validates_presence_of :title, :subtitle, :topic, :body

  mount_uploader :main_image, ImageUploader
  mount_uploader :thumb_nail, ImageUploader

  scope :reverse_date_order, -> { order("blogs.created_at DESC") }
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :blog

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/contact.rb
class Contact

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActiveModel::Callbacks

  attr_accessor :name, :email, :phone, :subject, :message

  validates :name, :message, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email, :id
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }

  scope :reverse_date_order, -> { order("leads.created_at DESC") }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart, optional: true

  scope :title_order, -> { order("line_items.title ASC") }

  def total_price
    quantity * price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_type: { 
    "Check" => 0,
    "Credit card" => 1, 
    "Purchase order" => 2
  }

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  has_many :line_items, dependent: :destroy

  def add_line_items_from_cart cart
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_no_line_items

  extend FriendlyId
  friendly_id :title, use: :slugged
  
  validates :title, :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true

  validates :thumb_nail, :main_image, allow_blank: true, format: { 
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  mount_uploader :main_image, ImageUploader
  mount_uploader :thumb_nail, ImageUploader

  scope :title_order, -> { order("products.title ASC") }

  private

  def ensure_no_line_items
    unless line_items.empty?
      errors.add(:base, 'Line items present')
      throw :abort  
    end
  end

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  after_create :email_purchaser

  def to_param
    uuid
  end

  def email_purchaser
    PurchaseMailer.purchase_receipt(self).deliver
  end

end

app/models/retreat.rb
class Retreat < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, :overview, :start_date, :end_date, presence: true

  scope :reverse_date_order, -> { order("retreats.created_at DESC") }
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates_presence_of :name, :summary, :biography

  mount_uploader :main_image, ImageUploader
  mount_uploader :thumb_nail, ImageUploader

  scope :name_order, -> { order("teachers.name ASC") }
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :blogs
  validates_presence_of :title

  scope :title_order, -> { order("topics.title ASC") }

  def self.with_blogs
    includes(:blogs).where.not(blogs: { id: nil } )
  end
end

app/models/user.rb
class User < ApplicationRecord

  # PeterGate Roles: the :user role is added by default
  # The multiple option can be set true if users have multiple roles

  petergate(roles: [:site_admin, :teacher, :tenant_admin, :tenant_member], multiple: false)

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  has_many :blogs
  has_many :comments, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  
  def blog_status_text blog
    blog.draft? ? t(:publish) : t(:unpublish)
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/shared/_blogs.html.erb
<div class="page-header">
  <%= render 'shared/page_title', title: t(:blog_index_title) %>
  <ul class="actions form-inline">
    <li><%= link_to t(:new), new_blog_path, class: "new" if logged_in?(:site_admin, :teacher) %></li>
    <%= search_form_for @q do |f| %>
      <%= f.search_field :body_cont, class: "form-control mb-2", placeholder: t(:search) %>
       <button class="btn btn-outline-success mb-2" type="submit"><%= t(:search) %></button>
    <% end %>
  </ul>
</div>
<br />
<div class="row row-offcanvas row-offcanvas-right">
  <div class="col-sm-10">
    <p class="float-right d-md-none">
      <button type="button" class="btn btn-primary btn-sm" data-toggle="offcanvas">Toggle nav</button>
    </p>
    <div class="row justify-content-center">
      <%= will_paginate @blogs %>
    </div>
    <div class="card-deck">
        <%= render @blogs %>
    </div><br />
    <div class="row justify-content-center">
      <%= will_paginate @blogs %>
    </div>
  </div>
  <div class="col-sm-2 sidebar-offcanvas" id="sidebar">
      <%= render 'shared/blogs_sidebar' %>
  </div>
</div>

app/views/shared/_blogs_sidebar.html.erb
<div class="blog-sidebar">
  <div class="sidebar-module">
    <h4><%= t(:topics) %></h4>
    <% @sidebar_topics.title_order.each do |topic| %>
      <%= link_to topic.title, topic_path(topic) %><br/>
    <% end %><br />
    <h4><%= t(:tags) %></h4>
    <div id='tag_cloud'>
      <% if logged_in?(:site_admin, :teacher) %>
        <% tag_cloud Blog.tag_counts.order("name asc"), %w{s m l} do |tag, css_class| %>
          <%= link_to tag.name, tag_path(tag.name), class: css_class %>&nbsp;
        <% end %>
      <% else %>
        <% tag_cloud Blog.published.tag_counts.order("name asc"), %w{s m l} do |tag, css_class| %>
          <%= link_to tag.name, tag_path(tag.name), class: css_class %>&nbsp;
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_charge.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container"> 
    <div class="row">
      <div class="col-md-12 no-padding">
        <div class="alert alert-alert %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <h6>
            <%= raw t('errors.template.header', count: obj.errors.count,
                model: t('activerecord.models.' + obj.class.to_s.downcase )) %>&nbsp;
            <%= t('errors.template.body') %>
          </h6>
          <ul>
            <% obj.errors.full_messages.each do | msg | %>
              <li><%= raw msg %></li>
            <% end %>
          </ul> 
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_images.html.erb
<div class="form-group">
  <label class="btn btn-info">
    <%= t(:upload_main_image) %> <%= f.file_field :main_image,
        style: "display:none;" %>
  </label>
  <% if f.object.main_image? %>
    <%= image_tag f.object.main_image.url %>
    <%= f.label t(:remove_main_image) %>
    <%= f.check_box :remove_main_image %> 
  <% end %>
</div>
<%= f.hidden_field :main_image_cache %>
<div class="form-group">
  <label class="btn btn-info">
    <%= t(:upload_thumb_nail) %> <%= f.file_field :thumb_nail,
        style: "display:none;" %>
  </label>
   <% if f.object.thumb_nail? %>
    <%= image_tag f.object.thumb_nail.url %>
    <%= f.label t(:remove_thumb_nail) %>
    <%= f.check_box :remove_thumb_nail %> 
  <% end %>
</div>
<%= f.hidden_field :thumb_nail_cache %>

app/views/shared/_page_title.html.erb
<h1><%= title %></h1>