config/routes.rb
Rails.application.routes.draw do  
  scope "(:locale)" do
    devise_for :users

    get 'pages/home'
    get '/about',             to: 'pages#about'
    get '/privacy_policy',    to: 'pages#privacy_policy'   
    #get '/products',          to: 'pages#products'
    get 'purchases/show',     to: 'purchases#show'
    #get '/retreat',           to: 'pages#retreat'
    get '/services',          to: 'pages#services'
    get '/store_index',       to: 'store#index'
    get 'tags/:tag',          to: 'blogs#index', as: :tag
    get '/terms_of_service',  to: 'pages#terms_of_service'

    resources :blogs do 
      member do 
        get :toggle_status
      end
      get 'page/:page', action: :index, on: :collection
    end
    resources :carts
    resources :charges
    resources :contacts, only: [:new, :create]
    resources :leads
    resources :line_items
    resources :orders
    resources :photos
    resources :products do
      get :who_bought, on: :member
    end
    resources :purchases, only: [:show]
    resources :retreats do
      get '/import', action: :import, on: :collection
    end
    resources :subscriptions
    resources :teachers
    resources :topics, only: [:index, :show]

    mount ActionCable.server => '/cable'
  
    root to: 'pages#home'
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  acts_as_taggable
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  belongs_to :topic
  has_many :comments, dependent: :destroy
  validates_presence_of :title, :subtitle, :topic, :body

  mount_uploader :main_image, ImageUploader
  mount_uploader :thumb_nail, ImageUploader

  scope :reverse_date_order, -> { order("blogs.created_at DESC") }
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :blog

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/contact.rb
class Contact

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActiveModel::Callbacks

  attr_accessor :name, :email, :phone, :subject, :message

  validates :name, :message, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email, :id
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }

  scope :reverse_date_order, -> { order("leads.created_at DESC") }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart, optional: true

  scope :title_order, -> { order("line_items.title ASC") }

  def total_price
    quantity * price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_type: { 
    "Check" => 0,
    "Credit card" => 1, 
    "Purchase order" => 2
  }

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  has_many :line_items, dependent: :destroy

  def add_line_items_from_cart cart
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_no_line_items

  extend FriendlyId
  friendly_id :title, use: :slugged
  
  validates :title, :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true

  validates :thumb_nail, :main_image, allow_blank: true, format: { 
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  mount_uploader :main_image, ImageUploader
  mount_uploader :thumb_nail, ImageUploader

  scope :title_order, -> { order("products.title ASC") }

  private

  def ensure_no_line_items
    unless line_items.empty?
      errors.add(:base, 'Line items present')
      throw :abort  
    end
  end

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  after_create :email_purchaser

  def to_param
    uuid
  end

  def email_purchaser
    PurchaseMailer.purchase_receipt(self).deliver
  end

end

app/models/retreat.rb
class Retreat < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, :overview, :start_date, :end_date, presence: true

  scope :reverse_date_order, -> { order("retreats.created_at DESC") }
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates_presence_of :name, :summary, :biography

  mount_uploader :main_image, ImageUploader
  mount_uploader :thumb_nail, ImageUploader

  scope :name_order, -> { order("teachers.name ASC") }
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :blogs
  validates_presence_of :title

  scope :title_order, -> { order("topics.title ASC") }

  def self.with_blogs
    includes(:blogs).where.not(blogs: { id: nil } )
  end
end

app/models/user.rb
class User < ApplicationRecord

  # PeterGate Roles: the :user role is added by default
  # The multiple option can be set true if users have multiple roles

  petergate(roles: [:site_admin, :teacher, :tenant_admin, :tenant_member], multiple: false)

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  has_many :blogs
  has_many :comments, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /carts
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)

    if @cart.save
      redirect_to @cart, notice: 'Cart was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /carts/1
  def update
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Cart was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:card_id] = nil
    redirect_to store_index_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  
  def blog_status_text blog
    blog.draft? ? t(:publish) : t(:unpublish)
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
<h2><%= t(:cart) %></h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= t(:product)  %></th>
      <th><%= t(:quantity) %></th>
      <th><%= t(:price)    %> </th>
      <th><%= t(:total)    %></th>
      <th class="fit"><%= t(:actions) %></th>
    </tr>
  </thead>
  <tbody>
    <%= render cart.line_items %>
    <tr class="total_line">
      <td colspan="2"><%= t(:total) %></td>
      <td></td>
      <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
      <td></td>
    </tr>
  </tbody>
</table>

<%= link_to t(:checkout), new_order_path, class: "checkout mr-1" %>
<%= link_to t(:empty_cart), cart_path(@cart), class: "empty_cart", 
        method: :delete, data: { confirm: t(:are_you_sure) } %>


<!--

<%= form_tag charges_path, id: 'chargeForm' do %>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <%= hidden_field_tag 'stripeToken' %>
  <%= hidden_field_tag 'amount', cart.total_price %>
  <%= hidden_field_tag 'stripeEmail' %>
  <%= hidden_field_tag 'product_id', 1 %>
  <div class="actions">
    <%= link_to t(:checkout), cart_path(@cart), class: "checkout mr-1", id: "btn-buy" %>
    <%= link_to t(:empty_cart), cart_path(@cart), class: "empty_cart", 
        method: :delete, data: { confirm: t(:are_you_sure) } %>
  </div>

  <script>
    var handler = StripeCheckout.configure({
      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
      token: function(token, arg) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("chargeForm").submit();
      }
    });
    document.getElementById('btn-buy').addEventListener('click', function(e) {
      handler.open({
        name: "Retreat Store",
        description: "Cart: #{cart.id}",
        amount: document.getElementById("amount").value
      });
      e.preventDefault();
    })
  </script>
<% end %>
<% end %>


-->

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>